---
title: "Stat 850 Project Proposal"
format: html
editor: visual
author: Addison Carrol, Sydney Graham
---

## Instructions

Each member of your team should modify this document in some way and push their modifications to the repository in a separate commit. This will ensure that you have set your repository up in a way that ensures all group members are working with the same repository.

Please ensure that you have set your git name and email address on your computer by **modifying** the following commands and running them in the terminal:

```         
git config --global user.name "Mona Lisa"
git config --global user.email "mona@lisa.com"
```

In the proposal as in the final report, all of your code chunks should be set so that `echo = F`, which prevents the code from being printed in the report. You should also set `message = F, warning = F`, which will reduce the amount of additional output which is present in the report. You can customize the execution of code in quarto by using additional options, some of which are detailed [here](https://quarto.org/docs/computations/execution-options.html).

```{r setup II, include=FALSE, eval=TRUE}
knitr::opts_chunk$set(eval = TRUE, echo = TRUE, message = FALSE, warning = FALSE)
```

## Data

### Source

The data we are using in this project comes from \[https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2021/2021-07-27/olympics.csv\].

Provide some code to read in the data (either stored in the repository or read in directly from the source).

```{R}
# Get the Data

# Read in with tidytuesdayR package 
# Install from CRAN via: install.packages("tidytuesdayR")

#install.packages("tidytuesdayR")

# This loads the readme and all the datasets for the week of interest
# Either ISO-8601 date or year/week works!
tuesdata <- tidytuesdayR::tt_load(2021, week = 31)

olympics <- tuesdata$olympics

#regions has additional information on the NOC codes and region
regions <- tuesdata$regions
```

### Description

This dataset contains information about the winter and summer Olympic athletes from the years 1896 to 2016, their team, weight, placing, sport, event, age, height.

It was collected from Tidy Tuesday where the data was scraped from www.sports-reference.com.

Here is a data dictionary showing each variable, the type of variable, units, and range of values that are possible:

+---------+-----------------------------------+-----------+---------+---------------------------------------------------------+
| Name    | Description                       | Type      | Units   | Range/Values                                            |
+=========+===================================+===========+=========+=========================================================+
| id      | Athlete ID                        | numeric   | NA      | 1 - 135571                                              |
+---------+-----------------------------------+-----------+---------+---------------------------------------------------------+
| name    | Athlete Name                      | character | NA      | Name and surname(s) (ex. Lawal Kolawole "Kola" Abdulai) |
+---------+-----------------------------------+-----------+---------+---------------------------------------------------------+
| sex     | Athlete Sex                       | character | NA      | F or M                                                  |
+---------+-----------------------------------+-----------+---------+---------------------------------------------------------+
| age     | Athlete Age                       | numeric   | years   | 10 - 97                                                 |
|         |                                   |           |         |                                                         |
|         |                                   |           |         | NA if unknown                                           |
+---------+-----------------------------------+-----------+---------+---------------------------------------------------------+
| height  | Athlete Height                    | numeric   | cm      | 127 - 226                                               |
|         |                                   |           |         |                                                         |
|         |                                   |           |         | NA if unknown                                           |
+---------+-----------------------------------+-----------+---------+---------------------------------------------------------+
| weight  | Athlete weight                    | numeric   | kg      | 25 - 214                                                |
|         |                                   |           |         |                                                         |
|         |                                   |           |         | NA if unknown                                           |
+---------+-----------------------------------+-----------+---------+---------------------------------------------------------+
| team    | Country/Team competing for        | character | NA      | country name (ex. Canada)                               |
+---------+-----------------------------------+-----------+---------+---------------------------------------------------------+
| noc     | National Olympic Committee region | character | NA      | 3 letter code of NOC (ex. CAN)                          |
+---------+-----------------------------------+-----------+---------+---------------------------------------------------------+
| games   | Olympic games name                | character | NA      | Year and season (ex. 2000 Summer)                       |
+---------+-----------------------------------+-----------+---------+---------------------------------------------------------+
| year    | Year of Olympics                  | numeric   | YYYY    | 1896 - 2016                                             |
+---------+-----------------------------------+-----------+---------+---------------------------------------------------------+
| season  | Season                            | character | NA      | winter or summer                                        |
+---------+-----------------------------------+-----------+---------+---------------------------------------------------------+
| city    | City of Olympic host              | character | NA      | City name (ex. Atlanta)                                 |
+---------+-----------------------------------+-----------+---------+---------------------------------------------------------+
| sport   | Sport                             | character | NA      | Sport title (ex. Rowing)                                |
+---------+-----------------------------------+-----------+---------+---------------------------------------------------------+
| event   | Specific event                    | character | NA      | Specific event title (ex. Rowing Men's Coxed Eights)    |
+---------+-----------------------------------+-----------+---------+---------------------------------------------------------+
| medal   | Medal won (if any)                | character | NA      | (Gold, Silver, Bronze or NA)                            |
+---------+-----------------------------------+-----------+---------+---------------------------------------------------------+

Below is the data for the supplementary data in the regions dataframe

+---------+----------------------------+-----------+---------+----------------------------------------+
| Name    | Description                | Type      | Units   | Range/Values                           |
+=========+============================+===========+=========+========================================+
| NOC     | National Olympic Committee | character | NA      | 3 letter code of NOC (ex. CAN)         |
+---------+----------------------------+-----------+---------+----------------------------------------+
| region  | Region associated with NOC | character | NA      | Region name (ex. Canada)               |
+---------+----------------------------+-----------+---------+----------------------------------------+
| notes   | Comments & alternate names | character | NA      | NA or alternate name (ex. Australasia) |
+---------+----------------------------+-----------+---------+----------------------------------------+

## Project Goals

Describe why this data is interesting and what you hope to do with it.

We will use \[dataset\] to explore the following topics:

-   How does global conflict influence the number of nations who participate in the Olympics?
-   How does body weight make a difference in the ability of an athlete to medal in a sport?
-   Are athletes with nicknames more likely to medal in Olympic events?
-   How has participation in track events changed over time? Are athletes competing in fewer events more recently? Has the length of their Olympic careers changed?

We expect to create

-   I want to make a graph that displays the number of countries that participate each year in the summer and winter olympics. I then would like to color code years of conflict to see if there is any relationship present.
-   Id like to make some sort of app where you can choose a weight range and it outputs the sports you may preform best in.
-   I would like to create a statistical model that compares performance of athletes with nicknames to those without. I think this should be accompanied by a figure summarizing the results.
-   A series of figures that describe the change in track events over time.

## Division of Labor

Describe how you plan to work together as a team. Set intermediate deadlines - what do you plan to have done by the project check-in? The more you have done (report/slides/code), the better feedback I can give you.

We plan on a collaborative effort primarily for our introduction and conclusion. Independently we will work on 2 interesting aspects of the data, as well as the data wrangling that goes along with it. We plan to meet once we get our preliminary analysis done to format the flow of the presentation. This will be the same in regards to the report aspect of this project.

By November 13th (Monday) we will have our data wrangling, and two individual analysis done. We will meet that week to pull together the intro and conclusion and identify any gaps. By the 21st (Tuesday) of November we aim to have the initial draft of the report done. We will turn this info in on the 24th (Friday) or earlier. We will make edits and be ready to film presentation on Dec 1st (Friday). Filming will occur on Dec 4th (Monday).

## Additional Comments

What concerns do you have about this project? This is your place to provide feedback about the project guidelines and ask clarifying questions for me to address either individually or in class, if the question is relevant to everyone.

How quickly will we get feedback from the initial feedback on the 24th? If we turn in earlier, do we get feedback earlier?
